package br.gov.caixa.sigsj.validacontacredito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.11
 * 2021-06-23T22:58:04.702-03:00
 * Generated source version: 3.3.11
 *
 */
@WebService(targetNamespace = "http://caixa.gov.br/sigsj/validacontacredito", name = "GSJPO700Port")
@XmlSeeAlso({br.gov.caixa.sigsj.validacontacredito.req.ObjectFactory.class, br.gov.caixa.sigsj.validacontacredito.resp.ObjectFactory.class})
public interface GSJPO700Port {

    @WebMethod
    @RequestWrapper(localName = "validacontacredito", targetNamespace = "http://caixa.gov.br/sigsj/validacontacredito/req", className = "br.gov.caixa.sigsj.validacontacredito.req.ProgramInterface")
    @ResponseWrapper(localName = "validacontacreditoResponse", targetNamespace = "http://caixa.gov.br/sigsj/validacontacredito/resp", className = "br.gov.caixa.sigsj.validacontacredito.resp.ProgramInterface")
    @WebResult(name = "ValidaContaCredito", targetNamespace = "http://caixa.gov.br/sigsj/validacontacredito/resp")
    public br.gov.caixa.sigsj.validacontacredito.resp.ProgramInterface.ValidaContaCredito validacontacredito(

        @WebParam(name = "ValidaContaCredito", targetNamespace = "http://caixa.gov.br/sigsj/validacontacredito/req")
        br.gov.caixa.sigsj.validacontacredito.req.ProgramInterface.ValidaContaCredito validaContaCredito
    );
}
