package br.gov.caixa.sigsj.validacontacredito;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.eclipse.microprofile.config.ConfigProvider;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.11
 * 2021-06-23T22:58:04.709-03:00
 * Generated source version: 3.3.11
 *
 */
@WebServiceClient(name = "GSJPO700Service",
                  wsdlLocation = "http://stfsaon005895-l:9000/mockGSJPO700HTTPSoapBinding?WSDL",
                  targetNamespace = "http://caixa.gov.br/sigsj/validacontacredito")
public class GSJPO700Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://caixa.gov.br/sigsj/validacontacredito", "GSJPO700Service");
    public final static QName GSJPO700Port = new QName("http://caixa.gov.br/sigsj/validacontacredito", "GSJPO700Port");
    static {
        URL url = null;
        try {
            //url = new URL("http://stfsaon005895-l:8000/mockGSJPO700HTTPSoapBinding?WSDL");
            url = new URL(ConfigProvider.getConfig().getValue("cicsws.validacredito.url", String.class));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GSJPO700Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://stfsaon005895-l:9000/mockGSJPO700HTTPSoapBinding?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public GSJPO700Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GSJPO700Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GSJPO700Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GSJPO700Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GSJPO700Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GSJPO700Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GSJPO700Port
     */
    @WebEndpoint(name = "GSJPO700Port")
    public GSJPO700Port getGSJPO700Port() {
        return super.getPort(GSJPO700Port, GSJPO700Port.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GSJPO700Port
     */
    @WebEndpoint(name = "GSJPO700Port")
    public GSJPO700Port getGSJPO700Port(WebServiceFeature... features) {
        return super.getPort(GSJPO700Port, GSJPO700Port.class, features);
    }

}
