
package br.gov.caixa.sigsj.validacontacredito;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.11
 * 2021-06-23T22:58:04.625-03:00
 * Generated source version: 3.3.11
 *
 */
public final class GSJPO700Port_GSJPO700Port_Client {

    private static final QName SERVICE_NAME = new QName("http://caixa.gov.br/sigsj/validacontacredito", "GSJPO700Service");

    private GSJPO700Port_GSJPO700Port_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GSJPO700Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GSJPO700Service ss = new GSJPO700Service(wsdlURL, SERVICE_NAME);
        GSJPO700Port port = ss.getGSJPO700Port();

        {
        System.out.println("Invoking validacontacredito...");
        br.gov.caixa.sigsj.validacontacredito.req.ProgramInterface.ValidaContaCredito _validacontacredito_validaContaCredito = null;
        br.gov.caixa.sigsj.validacontacredito.resp.ProgramInterface.ValidaContaCredito _validacontacredito__return = port.validacontacredito(_validacontacredito_validaContaCredito);
        System.out.println("validacontacredito.result=" + _validacontacredito__return);


        }

        System.exit(0);
    }

}
